# Generated by Django 5.2.15 on 2026-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(help_text='The source currency code (e.g., USD).', max_length=3, verbose_name='From Currency')),
                ('to_currency', models.CharField(help_text='The target currency code (e.g., INR).', max_length=3, verbose_name='To Currency')),
                ('rate', models.DecimalField(decimal_places=6, help_text='The conversion multiplier. Stored with 6 decimal places for precision.', max_digits=12, verbose_name='Exchange Rate')),
                ('effective_date', models.DateField(help_text='The date for which this exchange rate is valid.', verbose_name='Effective Date')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
    ]
