# Generated by Django 5.2.15 on 2026-06-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('groups', '0001_initial'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the expense (e.g. Dinner, Cab fare).', max_length=255, verbose_name='Description')),
                ('date', models.DateField(help_text='The date when the expense occurred.', verbose_name='Date')),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='The total amount of the transaction in the original currency.', max_digits=12, verbose_name='Original Amount')),
                ('original_currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], help_text='The currency in which the expense was originally paid.', max_length=3, verbose_name='Original Currency')),
                ('amount_inr', models.DecimalField(decimal_places=2, help_text='The converted transaction value in base currency (INR).', max_digits=12, verbose_name='Amount in INR')),
                ('split_type', models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact'), ('PERCENTAGE', 'Percentage'), ('SHARES', 'Shares')], help_text='The formula used to distribute shares.', max_length=15, verbose_name='Split Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VOID', 'Void'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', help_text='The current state of the expense.', max_length=15, verbose_name='Status')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTED', 'Imported')], default='MANUAL', help_text='Where the entry originated.', max_length=15, verbose_name='Source')),
                ('fx_rate_used', models.ForeignKey(blank=True, help_text='Exchange rate reference. Required if currency is not INR.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fxrate', verbose_name='FX Rate Used')),
                ('group', models.ForeignKey(help_text='The group this expense belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group', verbose_name='Group')),
                ('import_batch', models.ForeignKey(blank=True, help_text='Reference to import metadata batch. Null if MANUAL.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='imports.importbatch', verbose_name='Import Batch')),
                ('paid_by', models.ForeignKey(help_text='The user who paid the total amount.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL, verbose_name='Paid By')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount_inr', models.DecimalField(decimal_places=2, help_text="The user's calculated share in base currency (INR).", max_digits=12, verbose_name='Share Amount in INR')),
                ('expense', models.ForeignKey(help_text='The parent expense.', on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense', verbose_name='Expense')),
                ('user', models.ForeignKey(help_text='The user responsible for this split share.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
