# Generated by Django 5.2.15 on 2026-06-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The converted transaction value in base currency (INR).', max_digits=12, verbose_name='Amount in INR'),
        ),
    ]
