# Generated by Django 5.2.15 on 2026-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this batch was imported.', verbose_name='Imported At')),
                ('description', models.CharField(blank=True, help_text='Optional description or original file name of the import batch.', max_length=255, verbose_name='Description')),
            ],
        ),
    ]
