# Generated by Django 5.2.15 on 2026-06-13 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importbatch',
            name='created_at',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group where this import will be applied.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='groups.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='raw_file',
            field=models.FileField(blank=True, help_text='The uploaded CSV/JSON file.', null=True, upload_to='import_raw_files/', verbose_name='Raw File'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_APPLIED', 'Partially Applied')], default='PENDING_REVIEW', help_text='The current validation or approval status of this import batch.', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded.', null=True, verbose_name='Uploaded At'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='The user who uploaded this batch.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description or metadata regarding this import batch.', max_length=255, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_reference', models.CharField(help_text="Reference to the row in the source file (e.g., 'row 14').", max_length=100, verbose_name='Row Reference')),
                ('anomaly_type', models.CharField(help_text='The category of anomaly detected.', max_length=100, verbose_name='Anomaly Type')),
                ('description', models.TextField(help_text='Explanation of the detected data anomaly.', verbose_name='Description')),
                ('raw_row_data', models.JSONField(help_text='The original raw fields and values parsed from this row.', verbose_name='Raw Row Data')),
                ('suggested_action', models.TextField(help_text='Automated suggested resolution for this anomaly.', verbose_name='Suggested Action')),
                ('final_action', models.TextField(blank=True, help_text='The final resolution action applied by the reviewer.', null=True, verbose_name='Final Action')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified')], default='PENDING', help_text='The current review decision state of this anomaly.', max_length=30, verbose_name='Status')),
                ('import_batch', models.ForeignKey(help_text='The import batch this anomaly belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importbatch', verbose_name='Import Batch')),
            ],
        ),
    ]
