# Generated by Django 5.2.15 on 2026-06-13 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the expense sharing group.', max_length=255, verbose_name='Group Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the group was created.', verbose_name='Created At')),
                ('created_by', models.ForeignKey(help_text='The user who created this group.', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(help_text='The date when the user joined the group.', verbose_name='Joined At')),
                ('left_at', models.DateField(blank=True, help_text='The date when the user left the group. Null if membership is active.', null=True, verbose_name='Left At')),
                ('group', models.ForeignKey(help_text='The group associated with this membership.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group', verbose_name='Group')),
                ('user', models.ForeignKey(help_text='The user associated with this membership.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
