# Generated by Django 5.2.15 on 2026-06-13 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_inr', models.DecimalField(decimal_places=2, help_text='The settlement payment amount in INR.', max_digits=12, verbose_name='Amount in INR')),
                ('date', models.DateField(help_text='The date when the settlement payment was made.', verbose_name='Date')),
                ('note', models.TextField(blank=True, default='', help_text='Optional description or note regarding the payment (e.g., transaction reference).', verbose_name='Note')),
                ('group', models.ForeignKey(help_text='The group this settlement belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group', verbose_name='Group')),
                ('paid_by', models.ForeignKey(help_text='The user who paid the settlement amount.', on_delete=django.db.models.deletion.CASCADE, related_name='settlements_paid', to=settings.AUTH_USER_MODEL, verbose_name='Paid By')),
                ('paid_to', models.ForeignKey(help_text='The user who received the settlement amount.', on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to=settings.AUTH_USER_MODEL, verbose_name='Paid To')),
            ],
        ),
    ]
